#ifndef __APP_COOP_H
#define __APP_COOP_H

#include <stdint.h>

#define F21_COOP_RELEASE_CLEAR_CM       20.0f

typedef enum
{
    F21_COOP_MASTER_IDLE = 0,
    F21_COOP_MASTER_WAIT_TARGET,
    F21_COOP_MASTER_LOAD_DELAY,
    F21_COOP_MASTER_OUTBOUND_MAIN,
    F21_COOP_MASTER_OUTBOUND_CROSS_ADVANCE,
    F21_COOP_MASTER_OUTBOUND_TURN,
    F21_COOP_MASTER_ROOM_RUN,
    F21_COOP_MASTER_UNLOAD_WAIT,
    F21_COOP_MASTER_TURN_AROUND,
    F21_COOP_MASTER_RETURN_BRANCH,
    F21_COOP_MASTER_RETURN_CROSS_ADVANCE,
    F21_COOP_MASTER_RETURN_TURN,
    F21_COOP_MASTER_CLEAR_JUNCTION,
    F21_COOP_MASTER_RETURN_HOME,
    F21_COOP_MASTER_RETURN_HOME_TURN_AROUND,
    F21_COOP_MASTER_FINISH,
    F21_COOP_MASTER_STOP,
    F21_COOP_MASTER_FAULT
} F21CoopMasterState_t;

typedef enum
{
    F21_COOP_SLAVE_IDLE = 0,
    F21_COOP_SLAVE_WAIT_START,
    F21_COOP_SLAVE_GO_WAIT_MAIN,
    F21_COOP_SLAVE_GO_WAIT_CROSS_ADVANCE,
    F21_COOP_SLAVE_GO_WAIT_TURN,
    F21_COOP_SLAVE_GO_WAIT_ROOM,
    F21_COOP_SLAVE_YELLOW_WAIT,
    F21_COOP_SLAVE_LEAVE_WAIT_TURN_AROUND,
    F21_COOP_SLAVE_LEAVE_WAIT_BRANCH,
    F21_COOP_SLAVE_CROSS_TO_TARGET,
    F21_COOP_SLAVE_TARGET_ROOM_RUN,
    F21_COOP_SLAVE_UNLOAD_WAIT,
    F21_COOP_SLAVE_TARGET_TURN_AROUND,
    F21_COOP_SLAVE_RETURN_BRANCH,
    F21_COOP_SLAVE_RETURN_CROSS_ADVANCE,
    F21_COOP_SLAVE_RETURN_TURN,
    F21_COOP_SLAVE_RETURN_HOME,
    F21_COOP_SLAVE_RETURN_HOME_TURN_AROUND,
    F21_COOP_SLAVE_FINISH,
    F21_COOP_SLAVE_STOP,
    F21_COOP_SLAVE_FAULT
} F21CoopSlaveState_t;

void F21Coop_Init(void);
void F21Coop_Tick1ms(void);
void F21Coop_Task10ms(void);
void F21Coop_Task100ms(void);
void F21Coop_Task200ms(void);
void F21Coop_HandleKey(uint8_t key);
void F21Coop_ResetTask(void);
uint8_t F21Coop_IsModeSwitchAllowed(void);
void F21Coop_CancelYellowWait(void);

#endif
